site_name: 도밍고네
site_description: 클라우드/인프라에 대해 기록하는 기술 블로그입니다.
site_author: 이시영
site_url: https://syloa.github.io/
use_directory_urls: true

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - content.code.copy
    - toc.follow
    - navigation.top
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: cyan
      toggle:
        icon: material/weather-night
        name: 다크 모드로 전환
    - scheme: slate
      media: "(prefers-color-scheme: light)"
      primary: cyan
      toggle:
        icon: material/weather-sunny
        name: 라이트 모드로 전환

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
plugins:
  - search:
      lang: [en, ko]
  # - git-revision-date-localized:
      # type: date
      # enable_creation_date: true
      # fallback_to_build_date: false
      # enable_git_follow: false
      # enabled: true
      # strict: false
  - glightbox
  # - minify:
  #     minify_html: true
  #     minify_css: true
  #     minify_js: true   
  - tags:
      tags_file: index.md
  - mermaid2
  # - awesome-pages
  # - i18n:
  #     languages:
  #       - locale: en 
  #         name: English
  #         default: true
  #         build: true
  #         fallback_to: kr
  #       - locale: ko
  #         name: 한국어
  #         build: true
  #         fallback_to: en
      
extra:
  # alternate:
  #   - name: 한국어
  #     link: /ko/
  #     lang: ko
  #   - name: English
  #     link: /en/
  #     lang: en
  generator: false
  meta:
    google-site-verification: "google-site-verification=9enAp2_KQ_J2TbYSbYhtTF7RUfFLFytvhnAM0TeX8sg"
  analytics:
    provider: google
    property: G-RTV54E0RW7

# extra_css:
#   - stylesheets/extra.css
  
nav:
  - Home: index.md
  - Cloud & Infra: 
      - Compute:
        - Virutalization & Container: 
          - 01_가상화 기초와 하이퍼바이저 유형: cloud-infra/compute/virtualization-container/01-virtualization.md
          - 02_리눅스 컨테이너 기초와 작동 원리: cloud-infra/compute/virtualization-container/02-container.md
          # - 03_가상머신과 컨테이너의 차이점: cloud-infra/compute/virtualization-container/03-vm-container-diff.md\
        # - AWS Compute & Container:
        #   - 01_AWS의 가상화 기술: cloud-infra/compute/aws-compute/01-aws-virtualization.md
        #   - 02_AWS의 컨테이너 오케스트레이션 서비스: cloud-infra/compute/aws-compute/02-aws-container-orchestration.md
        #   - ECS:
        #     - 01_ECS 코어 아키텍쳐 및 구성 요소:
        #     - 02_ECS Networking:
        #     - 03_배포 전략과 서비스 디스커버리:
        #     - 04_보안 및 스토리지:
        #     - 05_운영 및 CI/CD:
        
  
  - Kubernetes: 
    # - Vanilla K8s:
    #   - 01_Kubernetes 기초: kubernetes/vanilla/01.md
    - EKS:
      - AEWS: 
        - AEWS 1주차:
          - AEWS 1주차 - EKS 소개 및 배포: kubernetes/eks/aews/aews-week01.md
        - AEWS 2주차:
          - AEWS 2주차 - EKS Networking: kubernetes/eks/aews/aews-week02-01.md
          - AEWS 2주차 - EKS Networking Hands-on: kubernetes/eks/aews/aews-week02-02.md
        - AEWS 3주차:
          - AEWS 3주차 - 1) EKS Pod Scaling: kubernetes/eks/aews/aews-week03-01.md
          - AEWS 3주차 - 2) EKS Node Scaling: kubernetes/eks/aews/aews-week03-02.md
          - AEWS 3주차 - 3) EKS Monitoring: kubernetes/eks/aews/aews-week03-03.md
  # - CS:
  #   - Database System: cs/database/01.md
  #   - Discrete Mathematics: cs/discrete mathematics/01.md
  #   - Security: cs/security/01.md
  
