site_name: 도밍고네
site_description: 클라우드/인프라에 대해 기록하는 기술 블로그입니다.
site_author: 이시영
site_url: https://syloa.github.io

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - content.code.copy
    - toc.follow
    - navigation.top
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: cyan
      toggle:
        icon: material/weather-night
        name: 다크 모드로 전환
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: cyan
      toggle:
        icon: material/weather-sunny
        name: 라이트 모드로 전환

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
      # fallback_to_build_date: true
      enable_git_follow: false
      type: date
  # - awesome-pages
  # - minify:
  #     minify_html: true
  #     minify_css: true
  #     minify_js: true   
  - tags:
      tags_file: index.md

      
extra:
  # alternate:
  #   - name: 한국어
  #     link: /
  #     lang: ko
  #   - name: English
  #     link: /en/
  #     lang: en
  generator: false
  meta:
    google-site-verification: "google-site-verification=Z8ZH9TF33fanUzlKxd0z2WZ9QI467VLNQ6CQ36er_Wc"

nav:
  - Home: index.md
  - Cloud: 
      - Virutalization: 
        - 가상화 기초와 하이퍼바이저 유형: cloud/virtualization/virtualization_01.md
        # - AWS의 가상화 기술: cloud/virtualization/virtualization_02.md
        # - 컨테이너와 가상 머신의 차이점: cloud/virtualization/virtualization_03.md
      - AWS: 
        - EKS: 
          - AEWS: 
            - AEWS 1주차 - EKS 소개 및 배포: cloud/aws/eks/aews/aews-week01.md
  # - Kubernetes: kubernetes/01.md
  # - CS:
  #   - Database System: cs/database/01.md
  #   - Discrete Mathematics: cs/discrete mathematics/01.md
  #   - Security: cs/security/01.md