site_name: 도밍고네
site_description: 클라우드/인프라에 대해 기록하는 기술 블로그입니다.
site_author: 이시영
site_url: https://syloa.github.io
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: cyan
      toggle:
        icon: material/weather-night
        name: 다크 모드로 전환
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      toggle:
        icon: material/weather-sunny
        name: 라이트 모드로 전환

plugins:
  - search
  - blog

extra:
  alternate:
    - name: 한국어
      link: /
      lang: ko
    - name: English
      link: /en/
      lang: en
  generator: false
  meta:
    google-site-verification: "google-site-verification=Z8ZH9TF33fanUzlKxd0z2WZ9QI467VLNQ6CQ36er_Wc"

nav:
  - Home: index.md
  - Cloud: 
      - Overview: Cloud/Overview.md
      - Virutalization: Cloud/Virtualization.md
      - AWS: 
        - EKS: 
          - AEWS: 
            - 1주차: Cloud/AWS/EKS/AEWS/AEWS 1주차.md
  - Kubernetes: Kubernetes/01.md
  - Computer Science:
    - Database System: Computer Science/Database/01.md
    - Discrete Mathematics: Computer Science/Discrete_Mathematics/01.md
    - Security: Computer Science/Computer_Security/01.md